### ISSUE TITLE
express 5

### ISSUE THREAD

**Issue by TrejGun** [xpepermint/query-types#3]
in express 5 you can't assign to req.query
so the correct way to use plugin would be

```js
import queryTypes from "query-types";
import qs from "qs";

app.set("query parser fn", str => queryTypes.parseObject(qs.parse(str)));
```

**Comment by xpepermint** [comment]
Hum ... I'm using `req.query` with express 5 in the same way as with version 4. Where exactly you see the problem?

**Comment by TrejGun** [comment]
in here
https://github.com/expressjs/express/blob/5.x/lib/request.js#L212
